version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotto
      MYSQL_USER: user
      MYSQL_PASSWORD: longpass
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql