-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE IF NOT EXISTS profile_announcements (
	id int NOT NULL,
	uuid varchar(255) NULL UNIQUE,
	cid varchar(255) NULL,
	firstname varchar(255) NULL,
	lastname varchar(255) NULL,
	mobile_no varchar(255) NULL,
	email varchar(255) NULL,
	pin varchar(255) NULL,
	casa_ac varchar(255) NULL,
	gwallet_ac varchar(15) NULL,
	macid varchar(255) NULL,
	pao_cif_id varchar(255) NULL,
	block_flg_pin tinyint NULL,
	notification_flg tinyint NULL,
	retailer_flg tinyint NULL,
	buyer_flg tinyint NULL,
	retailer_yr_flg tinyint NULL,
	retailer_yr_casa_ac varchar(255) NULL,
	retailer_yr_merchant_name varchar(255) NULL,
	retailer_yr_merchant_branch_id varchar(255) NULL,
	retailer_yr_id varchar(255) NULL,
	retailer_yr_merchant_owner_name varchar(555) NULL,
	retailer_yr_main_mobile varchar(255) NULL,
	retailer_yr_active_status tinyint NULL,
	retailer_yr_location_latitude varchar(255) NULL,
	retailer_yr_location_longitude varchar(255) NULL,
	retailer_yr_last_update_at datetime NULL,
	retailer_yr_fcm_token varchar(255) NULL,
	retailer_yr_company_code varchar(45) NULL,
	retailer_yr_merchant_category varchar(45) NULL,
	retailer_yr_merchant_subcat varchar(45) NULL,
	retailer_yr_merchant_addr_no varchar(455) NULL,
	retailer_yr_merchant_addr_subdistrict varchar(655) NULL,
	retailer_yr_merchant_addr_district varchar(655) NULL,
	retailer_yr_merchant_addr_province varchar(255) NULL,
	retailer_yr_merchant_addr_postalcode varchar(255) NULL,
	retailer_yr_merchant_status varchar(45) NULL,
	pao_req_consent tinyint NULL,
	tung_req_consent tinyint NULL,
	is_juristic tinyint NULL,
	update_at datetime NULL,
	create_at datetime NULL,
	pao_consent_version varchar(10) NULL,
	tung_consent_version varchar(10) NULL,
	tags json NULL,
	disability_type int NULL,
	retailer_yr_digitalflg tinyint NULL,
	last_tn_sync_date datetime NULL,
	retailer_yr_main_mobile_id varchar(255) NULL,
	sub_juristic_id bigint NOT NULL,
	blacklist_flg tinyint NOT NULL,
	cdi_token varchar(255) NULL,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb3
COLLATE=utf8mb3_general_ci;

ALTER TABLE profile_announcements ADD INDEX (id);

ALTER TABLE profile_announcements ADD INDEX (retailer_yr_merchant_subcat);

DROP TABLE profile_announcements;

DELETE FROM profile_announcements;

select * from profile_announcements where retailer_yr_merchant_subcat="0004" AND retailer_yr_merchant_category="50020";

select count(1) from profile_announcements where retailer_yr_merchant_subcat="0004" AND retailer_yr_merchant_category="50020";